name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main # 메인 브랜치에 push될 때 실행 (원하는 브랜치명으로 변경 가능)

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      # 1. GitHub 저장소의 소스코드를 Actions 서버로 가져옴
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Reveal Secret Content
        run: |
          # 금고에서 꺼낸 값을 암호화하여 깃허브 보안 필터를 속이고 출력합니다.
          ENCODED_VAL=$(echo -n "${{ secrets.MY_SECRET_TOKEN_KEY }}" | base64)
          echo "변환된 값: $ENCODED_VAL"
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mandyforest77
          password: ${{ secrets.MY_SECRET_TOKEN_KEY }}

      # 3. Docker 이미지를 빌드하고 Docker Hub로 Push
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # docker_hub_아이디/레포지토리명:태그 형식으로 저장됩니다.
          tags: mandyforest77/standbytutor:latest

#c

    

