name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main # 메인 브랜치에 push될 때 실행 (원하는 브랜치명으로 변경 가능)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 저장소의 소스코드를 Actions 서버로 가져옴
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Docker Hub 로그인을 위한 설정 수행
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mandyforest77
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Docker 이미지를 빌드하고 Docker Hub로 Push
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # docker_hub_아이디/레포지토리명:태그 형식으로 저장됩니다.
          tags: mandyforest77/standbytutor:latest

      # 2. 플러그인을 거치지 않고 깃허브 금고에서 순수 명령어로 직접 가져옵니다.
      - name: Log in to Docker Hub Direct
        env:
          # 시크릿을 플러그인에 넘기지 않고, 리눅스 환경변수에 직접 박아 넣습니다.
          RAW_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$RAW_PASS" | docker login -u mandyforest77 --password-stdin
