name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main # 메인 브랜치에 push될 때 실행 (원하는 브랜치명으로 변경 가능)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 저장소의 소스코드를 Actions 서버로 가져옴
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Docker Hub 로그인을 위한 설정 수행
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mandyforest77
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Docker 이미지를 빌드하고 Docker Hub로 Push
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # docker_hub_아이디/레포지토리명:태그 형식으로 저장됩니다.
          tags: mandyforest77/standbytutor:latest
